export const PRODUCTS_LIST_REQUEST = 'PRODUCTS_LIST_REQUEST'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'


export const PRODUCTS_DETAILS_REQUEST = 'PRODUCTS_DETAILS_REQUEST'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'

export const PRODUCTS_DELETE_REQUEST = "PRODUCTS_DELETE_REQUEST";
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
